# Generated by Django 6.0.5 on 2026-05-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='Sin puesto', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
