# Generated by Django 6.0.5 on 2026-05-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0002_empleado_puesto_alter_doctor_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
