# Generated by Django 6.0.5 on 2026-05-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0003_alter_producto_descripcion_and_more'),
        ('appVet', '0003_producto_imagen_servicio_imagen_and_more'),
    ]

    operations = [
    ]
