# Generated by Django 6.0.5 on 2026-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0004_merge_20260518_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='doctores/'),
        ),
    ]
