# Generated by Django 6.0.5 on 2026-05-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0005_doctor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
