# Generated by Django 6.0.5 on 2026-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVet', '0006_doctor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
    ]
